version: '3.1'

services:
    redis:
        image: redis:latest
        # command: redis-server --requirepass password_here
        environment: 
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - 6379:6379