version: '3.1'

services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379

    redis-cli:
        image: redis:latest
        links:
            - redis
        command: redis-cli -h redis

    # kafka
    # https://medium.com/better-programming/your-local-event-driven-environment-using-dockerised-kafka-cluster-6e84af09cd95
    zookeeper:
        image: confluentinc/cp-zookeeper:5.4.0
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000 
    broker:
        image: confluentinc/cp-server:5.4.0
        hostname: broker
        container_name: broker
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
            CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
            CONFLUENT_METRICS_ENABLE: 'true'
            CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous' 
    kafka-tools:
        image: confluentinc/cp-kafka:5.4.0
        hostname: kafka
        container_name: kafka
        command: ["tail", "-f", "/dev/null"]
        network_mode: "host"
    # kafka end

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        volumes:
            - /Users/mfathirirhas/.docker/rabbitmq/data/:/var/lib/rabbitmq/
            - /Users/mfathirirhas/.docker/rabbitmq/logs/:/var/log/rabbitmq/
            - /Users/mfathirirhas/.docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
        environment:
            RABBITMQ_ERLANG_COOKIE: cluster_cookie
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - 5672:5672
            - 15672:15672

    consul:
        image: consul
        ports:
            - "8500:8500"
