version: '3.1'

services:
  db:
    image: mysql:5.7
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: ''
    ports:
      - '3306:3306'
    # volumes:
    #   - /home/portela/Desenv/volumes/mysql:/var/lib/mysql    
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - mysql-compose-network
networks:
  mysql-compose-network:
    driver: bridge