version: '3.1'

services:
  db-mysql:
    image: mysql:5.7
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: ''
    ports:
      - '3306:3306'
    # volumes:
    #   - /home/portela/Desenv/volumes/mysql:/var/lib/mysql    
  db-postgre:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: tododb
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - mysql-compose-network
networks:
  mysql-compose-network:
    driver: bridge